hosts:
  example:
    url: https://gitlab.example.com
    token: TOKEN-MY
webhook_conf:
  tls:
    path: /etc/webhook/certs/
    cert_file: key.pem
    key_file: certificate.crt
    organization: flant.com
  webhook:
    rules:
    - operations: ["UPDATE", "CREATE", "DELETE"]
      rule:
        apiVersions: ["*"]
        apiGroups: ["apps", "networking.k8s.io", "extensions", ""]
        resources: ["deployments", "ingresses", "statefulsets", "daemonsets", "services"]
        scope: "*"
